In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:

date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
586 2019-06-26        2563       18       8       2019
623 2018-09-13        4597        3       2       2018
723 2018-12-07        2879        3       1       2018
431 2019-09-13        5012       13       3       2019
329 2019-03-05        5347        3       5       2019

### 2. Extract Month

In [10]:

date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [11]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

### Extract Days

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [14]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [15]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### Extract week of the year

In [32]:
date['date_week'] = date['date'].dt.isocalendar().week


date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

### Extract Quarter

In [17]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### Extract Semester

In [18]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### Extract Time elapsed between dates

In [19]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 30, 20, 36, 51, 196597)

In [20]:
today - date['date']

0     2486 days 20:36:51.196597
1     2968 days 20:36:51.196597
2     2899 days 20:36:51.196597
3     2601 days 20:36:51.196597
4     2824 days 20:36:51.196597
                 ...
995   2914 days 20:36:51.196597
996   2855 days 20:36:51.196597
997   2703 days 20:36:51.196597
998   2768 days 20:36:51.196597
999   2542 days 20:36:51.196597
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
(today - date['date']).dt.days

0      2486
1      2968
2      2899
3      2601
4      2824
       ...
995    2914
996    2855
997    2703
998    2768
999    2542
Name: date, Length: 1000, dtype: int64

In [33]:

# Months passed
np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44, 0)

0      82.0
1      98.0
2      95.0
3      85.0
4      93.0
       ...
995    96.0
996    94.0
997    89.0
998    91.0
999    84.0
Name: date, Length: 1000, dtype: float64

In [ ]:
time.info()

In [23]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [25]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time part

In [26]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [27]:
today - time['date']

0     4672 days 19:46:51.196597
1     4536 days 20:56:51.196597
2     5022 days 20:15:51.196597
3     4324 days 20:05:51.196597
4     4721 days 21:25:51.196597
                 ...
995   5311 days 19:46:51.196597
996   4632 days 21:22:51.196597
997   5097 days 20:59:51.196597
998   5213 days 21:02:51.196597
999   4485 days 21:11:51.196597
Name: date, Length: 1000, dtype: timedelta64[ns]

In [28]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.037320e+08
1      3.919858e+08
2      4.339738e+08
3      3.736660e+08
4      4.079716e+08
           ...
995    4.589416e+08
996    4.002818e+08
997    4.404564e+08
998    4.504790e+08
999    3.875803e+08
Name: date, Length: 1000, dtype: float64

In [29]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.728867e+06
1      6.533097e+06
2      7.232896e+06
3      6.227766e+06
4      6.799526e+06
           ...
995    7.649027e+06
996    6.671363e+06
997    7.340940e+06
998    7.507983e+06
999    6.459672e+06
Name: date, Length: 1000, dtype: float64

In [30]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      112147.780888
1      108884.947555
2      120548.264221
3      103796.097555
4      113325.430888
           ...
995    127483.780888
996    111189.380888
997    122348.997555
998    125133.047555
999    107661.197555
Name: date, Length: 1000, dtype: float64